### ISSUE TITLE
会议论文

### ISSUE THREAD

**Issue by DreamDQ** [bamtercelboo/Awesome-Law-NLP-Research-Work#1]
感谢您的分享，想咨询您下，自然语言处理方向有没有比较好发的会议论文呢？ 麻烦您了

**Comment by dalinvip** [comment]
这个您可以去查一下，国内的NLPCC(今年C类)、CCL，国外的还有很多。

**Comment by DreamDQ** [comment]
好的 谢谢您啦

**Comment by dalinvip** [comment]
没事，感谢关注。

**Comment by DreamDQ** [comment]
已关注，我们实验室要求英文还有ei检索的才给报销版印费TT😭 您如果有比较好投的期刊或者会议麻烦您给我推荐推荐哈   谢谢您了🎈

**Comment by dalinvip** [comment]
@DreamDQ 您在哪个实验室？
